<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="15295" started-at="2022-05-16T16:18:12 EET" finished-at="2022-05-16T16:18:28 EET">
    <groups>
    </groups>
    <test name="User registration using firefox" duration-ms="700" started-at="2022-05-16T16:18:12 EET" finished-at="2022-05-16T16:18:13 EET">
      <class name="createanaccounttests.CreateAnAccountTests">
        <test-method status="PASS" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:createanaccounttests.CreateAnAccountTests@4802796d]" name="setUpClass" is-config="true" duration-ms="308" started-at="2022-05-16T16:18:12 EET" finished-at="2022-05-16T16:18:13 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5b22b970]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="createValidAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:createanaccounttests.CreateAnAccountTests@4802796d]" name="createValidAccount" duration-ms="0" started-at="2022-05-16T16:18:13 EET" data-provider="CSV" finished-at="2022-05-16T16:18:13 EET">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
at org.testng.internal.Parameters.handleParameters(Parameters.java:767)
at org.testng.internal.Parameters.handleParameters(Parameters.java:704)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:904)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
at createanaccounttests.CreateAnAccountTests.getData(CreateAnAccountTests.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createValidAccount -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:createanaccounttests.CreateAnAccountTests@4802796d]" name="tearDownClass" is-config="true" duration-ms="22" started-at="2022-05-16T16:18:13 EET" finished-at="2022-05-16T16:18:13 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- createanaccounttests.CreateAnAccountTests -->
    </test> <!-- User registration using firefox -->
    <test name="User registration using chrome" duration-ms="15295" started-at="2022-05-16T16:18:12 EET" finished-at="2022-05-16T16:18:28 EET">
      <class name="purchaseproduct.PurchaseProduct">
        <test-method status="PASS" signature="setUp(java.lang.String,java.lang.Boolean)[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="setUp" is-config="true" duration-ms="34870" started-at="2022-05-16T16:17:37 EET" finished-at="2022-05-16T16:18:12 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="setUpClass" is-config="true" duration-ms="308" started-at="2022-05-16T16:18:12 EET" finished-at="2022-05-16T16:18:13 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@22d1886d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="purchaseProduct(java.lang.String,java.lang.String)[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="purchaseProduct" duration-ms="12737" started-at="2022-05-16T16:18:15 EET" data-provider="Excel" finished-at="2022-05-16T16:18:28 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[ashrytest@hotmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.23456789E8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Please check your data expected [My account - My Store] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Please check your data expected [My account - My Store] but found [Login - My Store]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at assertions.Assertions.assertOnPage(Assertions.java:15)
at purchaseproduct.PurchaseProduct.purchaseProduct(PurchaseProduct.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseProduct -->
        <test-method status="FAIL" signature="recoredFaliures(org.testng.ITestResult)[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="recoredFaliures" is-config="true" duration-ms="1" started-at="2022-05-16T16:18:28 EET" finished-at="2022-05-16T16:18:28 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=purchaseProduct status=FAILURE method=PurchaseProduct.purchaseProduct(java.lang.String,java.lang.String)[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[com.sun.proxy.$Proxy19 cannot be cast to org.openqa.selenium.TakesScreenshot]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: com.sun.proxy.$Proxy19 cannot be cast to org.openqa.selenium.TakesScreenshot
at basetests.BaseTests.recoredFaliures(BaseTests.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:772)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:748)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recoredFaliures -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="tearDownClass" is-config="true" duration-ms="2" started-at="2022-05-16T16:18:28 EET" finished-at="2022-05-16T16:18:28 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:purchaseproduct.PurchaseProduct@6a6cb05c]" name="tearDown" is-config="true" duration-ms="1019" started-at="2022-05-16T16:18:28 EET" finished-at="2022-05-16T16:18:29 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- purchaseproduct.PurchaseProduct -->
    </test> <!-- User registration using chrome -->
  </suite> <!-- All Test Suite -->
</testng-results>
